version: '3.9'

services:
  app:
    build:
      context: ./api  # Change the build context to the API folder
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_URL: "postgresql://tripleA:test@postgres:5432/tripleA_db?sslmode=disable"
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=tripleA
      - POSTGRES_DB=tripleA_db